/*
** EPITECH PROJECT, 2019
** RPG
** File description:
** enum.h
*/

#ifndef ENUM_H_
#define ENUM_H_

enum scene {main_menu, option_menu, exit_menu, inventory_menu, me_menu};

enum main_menu {BG_O_S0, BG1_O_S0, BG2_O_S0, CLOUD1_O_S0, CLOUD2_O_S0,
FLAMINGO_O_S0, LOGO_O_S0, HTW_O_S0, EXIT_B_S0, BACK_B_S0, NEW_B_S0, LOAD_B_S0,
CREDITS_B_S0, CLOSE_B_S0, MENU_S_S0, CLICK_S_S0, CURSOR_O_S0};

enum option_menu {OPTION_O_S1, CLOSE_B_S1, PLUS_B_S1, MINUS_B_S1, VOLUME_T_S1,
VSYNC_T_S1, CLICK_S_S1, CURSOR_O_S1};

enum inventory_menu {INVENTORY_O_S2, SWORD1_O_S2, SWORD2_O_S2, MAP_O_S2,
CURSOR_O_S2};

enum exit_menu {EXIT_B_S3, DESKTOP_B_S3, MENU_O_S3, CLOSE_B_S3, CLICK_S_S3,
CURSOR_O_S3};

enum me_menu {CLOSE_B_S4, ME_O_S4, CLICK_S_S4, NAME_T_S4, XP_T_S4, POS_T_S4,
LIFE_T_S4, CURSOR_O_S4};

enum town {SHAMAN_O_S5, SWORD_S_S5, PANNEL_O_S5, MUSIC_S_S5, CLICK_S_S5,
WALK_S_S5, TOWN_O_S5, DICK_O_S5, EMILY_O_S5, SHEEP_O_S5, JODI_O_S5, LEWIS_O_S5,
PIERRE_O_S5, ROBIN_O_S5, MINIMAP_O_S5, BOSS_S_S5, CURSOR_O_S5};

enum forest {SWORD_S_S6, MUSIC_S_S6, CLICK_S_S6, WALK_S_S6, FOREST_O_S6,
GHOST_O_S6, CURSOR_O_S6};

enum beach {SWORD_S_S7, MUSIC_S_S7, CLICK_S_S7, WALK_S_S7, BEACH_O_S7,
SKELETON_O_S7, CURSOR_O_S7};

enum map {SWORD_S_S8, MUSIC_S_S8, CLICK_S_S8, WALK_S_S8, MAP_O_S8, GOLEM_O_S8,
CURSOR_O_S8};

enum player {CHOOSE_O_S9, NAME_T_S9, LEFT_B_S9, RIGHT_B_S9, OK_B_S9,
CLOSE_B_S9, CURSOR_O_S9};

#endif /* ENUM_H_ */